server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://aws-database.cngugkkmqrvn.ap-southeast-1.rds.amazonaws.com:3306/test_db?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: tony0324
    password: tony810324
    driver-class-name: com.mysql.cj.jdbc.Driver

